version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: 'admin@example.com'
      N8N_BASIC_AUTH_PASSWORD: 'senha-segura'
      N8N_HOST: 'localhost'
      N8N_PORT: '5678'
      N8N_PROTOCOL: 'http'
      WEBHOOK_TUNNEL_URL: 'http://localhost:5678'
      N8N_SECURE_COOKIE: 'false'
    volumes:
      - /mnt/c/docker-data/n8n:/home/node/.n8n  # Usando caminho do WSL
    ports:
      - "5678:5678"
    networks:
      - webnet
    user: "node"  # Executa o contêiner como o usuário 'node' para evitar problemas de permissão

networks:
  webnet:
    driver: bridge